diagnostics: true
filter_auto_init: true
filter_data_rate: 100
imu_data_rate: 100
imu_gpu_corr_data_rate: 0
imu_mag_data_rate: -1
imu_overrange_statue_data_rate: -1
imu_raw_data_rate: -1
port: /dev/ttyACM0
use_device_timestamp: false
use_ros_time: true
